matrix:
  CI_SCALA_VERSION:
    - 2.12.7
  JDK_HOME:
    - /usr/share/jvm/jdk8
    - /usr/share/jvm/jdk11

clone:
  git:
    image: plugins/git
    tags: true
    recursive: true
    depth: 50

pipeline:
  restore_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/1.x, refs/tags/*, refs/pull/*/head ]
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    restore: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git

  tests:
    image: scalacenter/scala-docs:1.4
    group: build
    when:
      ref: [ refs/heads/1.x, refs/tags/*, refs/pull/*/head ]
    commands:
      - export DRONE_DIR="/drone"
      - export JAVA_HOME="$JDK_HOME"
      - git fetch --tags && git log | head -n 20
      - ./bin/run-ci.sh

  rebuild_cache:
    image: appleboy/drone-sftp-cache
    when:
      ref: [ refs/heads/1.x, refs/tags/*, refs/pull/*/head ]
      matrix:
        JDK_HOME: /usr/share/jvm/jdk8 # Only cache the results produced by the tests step for jdk8
    secrets: [ sftp_cache_username, sftp_cache_private_key, sftp_cache_server, sftp_cache_path ]
    rebuild: true
    mount:
      - /drone/.ivy2/cache
      - /drone/.coursier-cache
      - /drone/.sbt
      - /drone/.git
